export const ROUTES = {
  DASHBOARD: "/dashboard",
  PRODUCTS: "/products",
  PRODUCT_NEW: "/products/new",
  PRODUCT_DETAIL: (id: string) => `/products/${id}`,
  RECEIPTS: "/operations/receipts",
  RECEIPT_NEW: "/operations/receipts/new",
  RECEIPT_DETAIL: (id: string) => `/operations/receipts/${id}`,
  DELIVERIES: "/operations/deliveries",
  DELIVERY_NEW: "/operations/deliveries/new",
  DELIVERY_DETAIL: (id: string) => `/operations/deliveries/${id}`,
  TRANSFERS: "/operations/transfers",
  TRANSFER_NEW: "/operations/transfers/new",
  TRANSFER_DETAIL: (id: string) => `/operations/transfers/${id}`,
  ADJUSTMENTS: "/operations/adjustments",
  ADJUSTMENT_NEW: "/operations/adjustments/new",
  HISTORY: "/history",
  WAREHOUSES: "/settings/warehouses",
  SETTINGS: "/settings",
  ONBOARDING: "/onboarding",
  LOGIN: "/login",
  SIGNUP: "/signup",
  RESET_PASSWORD: "/reset-password",   // ← ADD THIS
};